# Generated by Django 4.1 on 2022-08-10 17:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("short_name", models.CharField(max_length=8, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "party_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addressbook.party",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tax_id", models.CharField(max_length=50)),
                ("vat_id", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("addressbook.party",),
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "party_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="addressbook.party",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("given_name", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
            bases=("addressbook.party",),
        ),
        migrations.CreateModel(
            name="PartyRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("PARENT", "PARENT"),
                            ("SIBLING", "SIBLING"),
                            ("PARTNER", "PARTNER"),
                        ],
                        default="PARENT",
                        max_length=100,
                    ),
                ),
                (
                    "party_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties_from",
                        to="addressbook.party",
                    ),
                ),
                (
                    "party_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parties_to",
                        to="addressbook.party",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("line_one", models.CharField(max_length=100)),
                ("line_two", models.CharField(max_length=100)),
                ("line_three", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state_province", models.CharField(max_length=20)),
                ("postal_code", models.CharField(max_length=20)),
                ("post_office_box", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=2)),
                (
                    "party_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="addressbook.party",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
