# Generated by Django 4.1 on 2022-08-10 17:57

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ("addressbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("MAIN", "MAIN"),
                    ("INVOICE", "INVOICE"),
                    ("DELIVERY", "DELIVERY"),
                ],
                default="MAIN",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="line_one",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="line_three",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="line_two",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="post_office_box",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="state_province",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
